//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.WSLOGIN {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws/", ConfigurationName="WSLOGIN.WSLOGIN")]
    public interface WSLOGIN {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/LoginRequest", ReplyAction="http://ws/WSLOGIN/LoginResponse")]
        Vista.WSLOGIN.LoginResponse Login(Vista.WSLOGIN.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ws/WSLOGIN/LoginRequest", ReplyAction="http://ws/WSLOGIN/LoginResponse")]
        System.Threading.Tasks.Task<Vista.WSLOGIN.LoginResponse> LoginAsync(Vista.WSLOGIN.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://ws/", Order=0)]
        public Vista.WSLOGIN.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Vista.WSLOGIN.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string pass;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://ws/", Order=0)]
        public Vista.WSLOGIN.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Vista.WSLOGIN.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSLOGINChannel : Vista.WSLOGIN.WSLOGIN, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSLOGINClient : System.ServiceModel.ClientBase<Vista.WSLOGIN.WSLOGIN>, Vista.WSLOGIN.WSLOGIN {
        
        public WSLOGINClient() {
        }
        
        public WSLOGINClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSLOGINClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLOGINClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSLOGINClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Vista.WSLOGIN.LoginResponse Vista.WSLOGIN.WSLOGIN.Login(Vista.WSLOGIN.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public int Login(string user, string pass) {
            Vista.WSLOGIN.LoginRequest inValue = new Vista.WSLOGIN.LoginRequest();
            inValue.Body = new Vista.WSLOGIN.LoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            Vista.WSLOGIN.LoginResponse retVal = ((Vista.WSLOGIN.WSLOGIN)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Vista.WSLOGIN.LoginResponse> Vista.WSLOGIN.WSLOGIN.LoginAsync(Vista.WSLOGIN.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Vista.WSLOGIN.LoginResponse> LoginAsync(string user, string pass) {
            Vista.WSLOGIN.LoginRequest inValue = new Vista.WSLOGIN.LoginRequest();
            inValue.Body = new Vista.WSLOGIN.LoginRequestBody();
            inValue.Body.user = user;
            inValue.Body.pass = pass;
            return ((Vista.WSLOGIN.WSLOGIN)(this)).LoginAsync(inValue);
        }
    }
}
