//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.INFORME_INSPECCION = new HashSet<INFORME_INSPECCION>();
            this.INFORME_MEDICION = new HashSet<INFORME_MEDICION>();
            this.INFORME_TERMOGRAFIA = new HashSet<INFORME_TERMOGRAFIA>();
            this.USUARIO = new HashSet<USUARIO>();
            this.INFORME_VERIFICACION = new HashSet<INFORME_VERIFICACION>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
        }
    
        public string RUT_CLIENTE { get; set; }
        public string PRIMER_NOMBRE { get; set; }
        public string SEGUNDO_NOMBRE { get; set; }
        public string AP_PATERNO { get; set; }
        public string AP_MATERNO { get; set; }
        public string DIRECCION { get; set; }
        public int TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public int ID_COMUNA { get; set; }
        public Nullable<int> ID_TIPO_CLIENTE { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<INFORME_INSPECCION> INFORME_INSPECCION { get; set; }
        public virtual ICollection<INFORME_MEDICION> INFORME_MEDICION { get; set; }
        public virtual ICollection<INFORME_TERMOGRAFIA> INFORME_TERMOGRAFIA { get; set; }
        public virtual ICollection<USUARIO> USUARIO { get; set; }
        public virtual ICollection<INFORME_VERIFICACION> INFORME_VERIFICACION { get; set; }
        public virtual TIPO_CLIENTE TIPO_CLIENTE { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
    }
}
