//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
        public CLIENTE()
        {
            this.BANCO_ESTADO = new HashSet<BANCO_ESTADO>();
            this.INFORME = new HashSet<INFORME>();
            this.LOGIN = new HashSet<LOGIN>();
            this.PAGO = new HashSet<PAGO>();
            this.SOLICITUD = new HashSet<SOLICITUD>();
            this.VIVIENDA = new HashSet<VIVIENDA>();
        }
    
        public string RUT_CLIENTE { get; set; }
        public string PRIMER_NOMBRE { get; set; }
        public string SEGUNDO_NOMBRE { get; set; }
        public string AP_PATERNO { get; set; }
        public string AP_MATERNO { get; set; }
        public string DIRECCION { get; set; }
        public decimal TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string HIPOTECARIO { get; set; }
        public decimal ID_COMUNA { get; set; }
    
        public virtual ICollection<BANCO_ESTADO> BANCO_ESTADO { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<INFORME> INFORME { get; set; }
        public virtual ICollection<LOGIN> LOGIN { get; set; }
        public virtual ICollection<PAGO> PAGO { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD { get; set; }
        public virtual ICollection<VIVIENDA> VIVIENDA { get; set; }
    }
}
