//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMUNA
    {
        public COMUNA()
        {
            this.CLIENTE = new HashSet<CLIENTE>();
            this.TECNICO = new HashSet<TECNICO>();
            this.VIVIENDA = new HashSet<VIVIENDA>();
        }
    
        public decimal ID_COMUNA { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<CLIENTE> CLIENTE { get; set; }
        public virtual ICollection<TECNICO> TECNICO { get; set; }
        public virtual ICollection<VIVIENDA> VIVIENDA { get; set; }
    }
}
