//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESCUENTO
    {
        public DESCUENTO()
        {
            this.PAGO = new HashSet<PAGO>();
        }
    
        public decimal ID_DESCUENTO { get; set; }
        public decimal VALOR { get; set; }
    
        public virtual ICollection<PAGO> PAGO { get; set; }
    }
}
