//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class EQUIPO_TECNICO
    {
        public EQUIPO_TECNICO()
        {
            this.TECNICO = new HashSet<TECNICO>();
        }
    
        public decimal ID_EQUIPO { get; set; }
        public string NOMBRE { get; set; }
        public decimal ID_AGENDA { get; set; }
        public decimal ID_INSUMO { get; set; }
    
        public virtual AGENDA AGENDA { get; set; }
        public virtual INSUMO INSUMO { get; set; }
        public virtual ICollection<TECNICO> TECNICO { get; set; }
    }
}
