//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORME_MEDICION
    {
        public int NUM_FORMULARIO { get; set; }
        public string ESTADO_SERVICIO { get; set; }
        public System.DateTime FECHA_INSP { get; set; }
        public string RESULTADO { get; set; }
        public int NUM_HABITACIONES { get; set; }
        public int NUM_PISOS { get; set; }
        public string OBSERVACION { get; set; }
        public int AREA_REGIS { get; set; }
        public int AREA_REAL { get; set; }
        public int SUP_UTIL_REGIS { get; set; }
        public int SUP_UTIL_REAL { get; set; }
        public int SUP_CONSTR_REGIS { get; set; }
        public int SUP_CONSTR_REAL { get; set; }
        public int SUP_ELEM_REGIS { get; set; }
        public Nullable<int> SUP_ELEM_REAL { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string RUT_TECNICO { get; set; }
        public int ID_TIPO { get; set; }
        public int ID_AGRUP { get; set; }
        public int ID_SOLICITUD { get; set; }
    
        public virtual AGRUPAMIENTO AGRUPAMIENTO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual SOLICITUD SOLICITUD { get; set; }
        public virtual TECNICO TECNICO { get; set; }
        public virtual TIPO_VIVIENDA TIPO_VIVIENDA { get; set; }
    }
}
