//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORME
    {
        public long NUM_FORMULARIO { get; set; }
        public string ESTADO_SERVICIO { get; set; }
        public System.DateTime FECHA_INSP { get; set; }
        public string RESULTADO { get; set; }
        public int NUM_HABITACIONES { get; set; }
        public int NUM_PISOS { get; set; }
        public string OBSERVACION { get; set; }
        public string HABITABILIDAD { get; set; }
        public string TERMICA { get; set; }
        public string FUEGO { get; set; }
        public Nullable<int> AREA_REGIS { get; set; }
        public Nullable<int> AREA_REAL { get; set; }
        public Nullable<int> SUP_CONSTR_REGIS { get; set; }
        public Nullable<int> SUP_CONSTR_REAL { get; set; }
        public Nullable<int> EMISIVIDAD { get; set; }
        public Nullable<int> TEMP_REFLEJADA { get; set; }
        public Nullable<int> DISTANCIA { get; set; }
        public Nullable<int> HUMEDAD_REL { get; set; }
        public Nullable<int> TEMP_ATMOSFERICA { get; set; }
        public string RUT_CLIENTE { get; set; }
        public string RUT_TECNICO { get; set; }
        public int ID_TIPO { get; set; }
        public int ID_AGRUP { get; set; }
        public int ID_SOLICITUD { get; set; }
        public int ID_ALCANTARILLADO { get; set; }
        public int ID_GAS { get; set; }
        public int ID_ELECTRICA { get; set; }
        public int ID_AGUA { get; set; }
        public int ID_AGUA_POTABLE { get; set; }
        public string DIRECCION_VIVIENDA { get; set; }
        public string CONSTRUCTORA { get; set; }
        public int ID_COMUNA { get; set; }
    
        public virtual AGRUPAMIENTO AGRUPAMIENTO { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual INST_AGUA_POTABLE INST_AGUA_POTABLE { get; set; }
        public virtual INST_ALCANTARILLADO INST_ALCANTARILLADO { get; set; }
        public virtual INST_ELECTRICA INST_ELECTRICA { get; set; }
        public virtual INST_GAS INST_GAS { get; set; }
        public virtual RED_AGUA RED_AGUA { get; set; }
        public virtual SOLICITUD SOLICITUD { get; set; }
        public virtual TECNICO TECNICO { get; set; }
        public virtual TIPO_VIVIENDA TIPO_VIVIENDA { get; set; }
        public virtual COMUNA COMUNA { get; set; }
    }
}
