//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INFORME
    {
        public INFORME()
        {
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public decimal NUM_FORMULARIO { get; set; }
        public string ESTADO_SERVICIO { get; set; }
        public string RESULTADO { get; set; }
        public string OBSERVACION { get; set; }
        public System.DateTime FECHA_INSP { get; set; }
        public System.DateTime HORA_INSP { get; set; }
        public string RUT_TECNICO { get; set; }
        public decimal ID_VIVENDA { get; set; }
        public string RUT_CLIENTE { get; set; }
        public decimal ID_INSUMO { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual INSUMO INSUMO { get; set; }
        public virtual TECNICO TECNICO { get; set; }
        public virtual VIVIENDA VIVIENDA { get; set; }
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
