//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSP_SERVICIOS
    {
        public decimal ID_SERVICIO { get; set; }
        public decimal ID_ARTICULO { get; set; }
        public decimal ID_ALCANTARILLADO { get; set; }
        public decimal ID_ELECTRICA { get; set; }
        public decimal ID_AGUA_POTABLE { get; set; }
        public decimal ID_GAS { get; set; }
        public decimal ID_AGUA { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual ART_SANITARIO ART_SANITARIO { get; set; }
        public virtual INST_AGUA_POTABLE INST_AGUA_POTABLE { get; set; }
        public virtual INST_ALCANTARILLADO INST_ALCANTARILLADO { get; set; }
        public virtual INST_ELECTRICA INST_ELECTRICA { get; set; }
        public virtual INST_GAS INST_GAS { get; set; }
        public virtual SERVICIO SERVICIO { get; set; }
        public virtual RED_AGUA RED_AGUA { get; set; }
    }
}
