//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INST_AGUA_POTABLE
    {
        public INST_AGUA_POTABLE()
        {
            this.INFORME_INSPECCION = new HashSet<INFORME_INSPECCION>();
        }
    
        public int ID_AGUA_POTABLE { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<INFORME_INSPECCION> INFORME_INSPECCION { get; set; }
    }
}
