//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMO
    {
        public int ID_INSUMO { get; set; }
        public string NOMBRE { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> ID_EQUIPO { get; set; }
    
        public virtual EQUIPO_TECNICO EQUIPO_TECNICO { get; set; }
    }
}
