//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSUMO
    {
        public INSUMO()
        {
            this.EQUIPO_TECNICO = new HashSet<EQUIPO_TECNICO>();
        }
    
        public int ID_INSUMO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<EQUIPO_TECNICO> EQUIPO_TECNICO { get; set; }
    }
}
