//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN
    {
        public string NOMBRE_USUARIO { get; set; }
        public string PASSWORD { get; set; }
        public string RUT_CLIENTE { get; set; }
    
        public virtual CLIENTE CLIENTE { get; set; }
    }
}
