//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICION_M2
    {
        public decimal ID_SERVICIO { get; set; }
        public decimal AREA_TOTAL_REAL { get; set; }
        public decimal AREA_TOTAL_REG { get; set; }
        public decimal SUP_UTIL_REAL { get; set; }
        public decimal SUP_UTIL_REG { get; set; }
        public decimal SUP_CONST_REAL { get; set; }
        public decimal SUP_CONST_REG { get; set; }
        public decimal SUP_ELE_COM_REAL { get; set; }
        public decimal SUP_ELE_COM_REG { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
