//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public int ID_PAGO { get; set; }
        public int VALOR { get; set; }
        public int DESCUENTO { get; set; }
        public int ID_SOLICITUD { get; set; }
    
        public virtual SOLICITUD SOLICITUD { get; set; }
    }
}
