//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGION
    {
        public REGION()
        {
            this.COMUNA = new HashSet<COMUNA>();
            this.VIVIENDA = new HashSet<VIVIENDA>();
        }
    
        public decimal ID_REGION { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<COMUNA> COMUNA { get; set; }
        public virtual ICollection<VIVIENDA> VIVIENDA { get; set; }
    }
}
