//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public SERVICIO()
        {
            this.INFORME = new HashSet<INFORME>();
            this.SOLICITUD1 = new HashSet<SOLICITUD>();
        }
    
        public decimal ID_SERVICIO { get; set; }
        public string NOMBRE { get; set; }
        public decimal ID_SOLICITUD { get; set; }
    
        public virtual INSP_SERVICIOS INSP_SERVICIOS { get; set; }
        public virtual MEDICION_M2 MEDICION_M2 { get; set; }
        public virtual SOLICITUD SOLICITUD { get; set; }
        public virtual TERMOGRAFIA TERMOGRAFIA { get; set; }
        public virtual VERIF_INST_TERMINACION VERIF_INST_TERMINACION { get; set; }
        public virtual ICollection<INFORME> INFORME { get; set; }
        public virtual ICollection<SOLICITUD> SOLICITUD1 { get; set; }
    }
}
