//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public SOLICITUD()
        {
            this.SERVICIO = new HashSet<SERVICIO>();
        }
    
        public decimal ID_SOLICITUD { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public string HORA_SOLICITUD { get; set; }
        public string RUT_CLIENTE { get; set; }
        public decimal ID_AGENDA { get; set; }
    
        public virtual AGENDA AGENDA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual ICollection<SERVICIO> SERVICIO { get; set; }
    }
}
