//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLICITUD
    {
        public SOLICITUD()
        {
            this.INFORME_INSPECCION = new HashSet<INFORME_INSPECCION>();
            this.INFORME_MEDICION = new HashSet<INFORME_MEDICION>();
            this.INFORME_TERMOGRAFIA = new HashSet<INFORME_TERMOGRAFIA>();
            this.INFORME_VERIFICACION = new HashSet<INFORME_VERIFICACION>();
        }
    
        public int ID_SOLICITUD { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public string HORA_SOLICITUD { get; set; }
        public string DIRECCION_VIVIENDA { get; set; }
        public string CONSTRUCTORA { get; set; }
        public string RUT_CLIENTE { get; set; }
        public int ID_AGENDA { get; set; }
        public int ID_PAGO { get; set; }
        public int ID_COMUNA { get; set; }
        public int ID_SERVICIO { get; set; }
    
        public virtual AGENDA AGENDA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        public virtual PAGO PAGO { get; set; }
        public virtual COMUNA COMUNA { get; set; }
        public virtual ICollection<INFORME_INSPECCION> INFORME_INSPECCION { get; set; }
        public virtual ICollection<INFORME_MEDICION> INFORME_MEDICION { get; set; }
        public virtual ICollection<INFORME_TERMOGRAFIA> INFORME_TERMOGRAFIA { get; set; }
        public virtual SERVICIO SERVICIO1 { get; set; }
        public virtual ICollection<INFORME_VERIFICACION> INFORME_VERIFICACION { get; set; }
    }
}
