//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECNICO
    {
        public TECNICO()
        {
            this.INFORME = new HashSet<INFORME>();
        }
    
        public string RUT_TECNICO { get; set; }
        public string PRIMER_NOMBRE { get; set; }
        public string SEGUNDO_NOMBRE { get; set; }
        public string AP_PATERNO { get; set; }
        public string AP_MATERNO { get; set; }
        public string DIRECCION { get; set; }
        public decimal TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public decimal ID_EQUIPO { get; set; }
        public decimal ID_COMUNA { get; set; }
    
        public virtual COMUNA COMUNA { get; set; }
        public virtual EQUIPO_TECNICO EQUIPO_TECNICO { get; set; }
        public virtual ICollection<INFORME> INFORME { get; set; }
    }
}
