//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TERMOGRAFIA
    {
        public decimal ID_SERVICIO { get; set; }
        public decimal EMISIVIDAD { get; set; }
        public decimal TEMP_REFLEJADA { get; set; }
        public decimal DISTANCIA { get; set; }
        public decimal HUM_RELATIVA { get; set; }
        public decimal TEMP_ATMOSFERICA { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
