//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_VIVIENDA
    {
        public TIPO_VIVIENDA()
        {
            this.VIVIENDA = new HashSet<VIVIENDA>();
        }
    
        public decimal ID_TIPO { get; set; }
        public string NOMBRE_TIPO { get; set; }
    
        public virtual ICollection<VIVIENDA> VIVIENDA { get; set; }
    }
}
