//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TITULO
    {
        public TITULO()
        {
            this.TECNICO = new HashSet<TECNICO>();
        }
    
        public decimal ID_TITULO { get; set; }
        public string NOMBRE { get; set; }
    
        public virtual ICollection<TECNICO> TECNICO { get; set; }
    }
}
