//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BibliotecaControlador
{
    using System;
    using System.Collections.Generic;
    
    public partial class VERIF_INST_TERMINACION
    {
        public decimal ID_SERVICIO { get; set; }
        public string ALTURA_MIN { get; set; }
        public string VENTANA_BANIO_COC { get; set; }
        public string VENTANA_LOC_HAB { get; set; }
        public string AISL_TECHO_60MM { get; set; }
        public string MUROS_ALBA_BLOQUE { get; set; }
        public string AISL_PISOS_50MM { get; set; }
        public string TAB_EXT_30MM { get; set; }
        public string SUP_VENT_MURO { get; set; }
        public string MUROS_CONTRAFUEGO { get; set; }
        public string MUROS_ADOSAM { get; set; }
        public string MUROS_ESTRUCT { get; set; }
        public string TECHO_CIELO_FALSO { get; set; }
        public string MUROS_ALB_EXT { get; set; }
        public string MUROS_ALB_EXT_1 { get; set; }
        public string MADERA_EST_1X4 { get; set; }
        public string PILAR_HA_15X15 { get; set; }
        public string MADERA_IMPREG { get; set; }
        public string MAD_TABIQ_2X4 { get; set; }
        public string ENTREMADO_PISO_2X6 { get; set; }
        public string INST_ELECTRICA { get; set; }
        public string INST_AGUA { get; set; }
        public string INST_ALCANTARILLADO { get; set; }
        public string INT_GAS { get; set; }
        public string OTRO { get; set; }
        public string OBSERVACIONES { get; set; }
    
        public virtual SERVICIO SERVICIO { get; set; }
    }
}
